export enum SportIcons {
  'Volleyball' = 'volleyball-ball',
  'Tennis' = 'table-tennis',
  'Track' = 'running',
  'Track and Field' = 'running',
  'Indoor Track' = 'running',
  'Winter Track and Field' = 'running',
  'Bowling' = 'bowling-ball',
  'Cross Country' = 'running',
  'Swimming' = 'swimmer',
  'Diving' = 'water',
  'Wrestling' = 'weight',
  'Baseball' = 'baseball-ball',
  'Softball' = 'baseball-ball',
  'Golf' = 'golf-ball',
  'Basketball' = 'basketball-ball',
  'Football' = 'football-ball',
  'Quiz' = 'brain',
  'Quick Recall' = 'brain',
  'Knowledge Bowl' = 'brain',
  'Soccer' = 'futbol',
  'Dance' = 'shoe-prints',
  'Lacrosse' = 'quidditch',
  'Sideline Cheer' = 'hand-sparkles',
  'Basketball Cheer' = 'hand-sparkles',
  'Football Cheer' = 'hand-sparkles',
  'Competitive Cheer' = 'hand-sparkles',
  'Gymnastics' = 'dumbell',
  'Band' = 'drum',
  'Field Hockey' = 'hockey-puck',
  'Hockey' = 'hockey-puck',
  'Athletic Training' = 'running',
}

export const SportNames = SportIcons;
