require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.5'

target 'LocalSportsTracker' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'LocalSportsTrackerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    installer.pods_project.targets.each do |target|
      # Explicitly catch the Yoga framework compilation target
      # if target.name == 'Yoga'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited) '
          # Suppress the literal operator space deprecation warning
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] << ' -Wno-deprecated-literal-operator'
          # 2. Prevent bitwise logical warnings from failing the Yoga compilation phase
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] << ' -Wno-error=bitwise-instead-of-logical'

            # Force Xcode to re-enable C++17 removed templates like unary_function
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= '$(inherited) '
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '"_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION=1" '
        end
      # end
    end
  end
end
